# Default initial positions for rv4frl's ros2_control fake system

initial_positions:
  rv4frl_joint_1: 0
  rv4frl_joint_2: 0
  rv4frl_joint_3: 0
  rv4frl_joint_4: 0
  rv4frl_joint_5: 0
  rv4frl_joint_6: 0