# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  rv4frl_joint_1:
    has_velocity_limits: true
    max_velocity: 7.3303828583761845
    has_acceleration_limits: true
    max_acceleration: 164.9
  rv4frl_joint_2:
    has_velocity_limits: true
    max_velocity: 5.8643062867009474
    has_acceleration_limits: true
    max_acceleration: 131.85
  rv4frl_joint_3:
    has_velocity_limits: true
    max_velocity: 4.3633231299858233
    has_acceleration_limits: true
    max_acceleration: 98.1
  rv4frl_joint_4:
    has_velocity_limits: true
    max_velocity: 9.4247779607693793
    has_acceleration_limits: true
    max_acceleration: 211.95
  rv4frl_joint_5:
    has_velocity_limits: true
    max_velocity: 10.873401239924673
    has_acceleration_limits: true
    max_acceleration: 244.57
  rv4frl_joint_6:
    has_velocity_limits: true
    max_velocity: 12.566370614359172
    has_acceleration_limits: true
    max_acceleration: 282.6