# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  rv4fr_joint_1:
    has_velocity_limits: true
    max_velocity: 7.8539816339744828
    has_acceleration_limits: true
    max_acceleration: 157.07
  rv4fr_joint_2:
    has_velocity_limits: true
    max_velocity: 7.8539816339744828
    has_acceleration_limits: true
    max_acceleration: 157.07
  rv4fr_joint_3:
    has_velocity_limits: true
    max_velocity: 5.2359877559829888
    has_acceleration_limits: true
    max_acceleration: 104.71
  rv4fr_joint_4:
    has_velocity_limits: true
    max_velocity: 9.4247779607693793
    has_acceleration_limits: true
    max_acceleration: 188.49
  rv4fr_joint_5:
    has_velocity_limits: true
    max_velocity: 10.873401239924673
    has_acceleration_limits: true
    max_acceleration: 217.48
  rv4fr_joint_6:
    has_velocity_limits: true
    max_velocity: 12.566370614359172
    has_acceleration_limits: true
    max_acceleration: 251.327412287